services:
  postgres:
    image: postgres:16-alpine
    container_name: railway12306-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: railway12306
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/railway12306-postgres/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  postgres_data: